version: '2'
checks:
  argument-count:
    config:
      threshold: 5
  method-complexity:
    config:
      threshold: 10

exclude_patterns:
  - vendor/
  - tests/

plugins:
  php:
    enabled: true
    config:
      paths:
        - src/