# https://help.github.com/en/categories/automating-your-workflow-with-github-actions
on:
  - pull_request
  - push

name: CI

# todo fix pipelines for github CI
jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}


    env:
      PHP_EXTENSIONS: none, dom, json, libxml, mbstring, openssl, pdo_mysql, phar, soap, tokenizer, xml, xmlwriter
      PHP_INI_VALUES: memory_limit=-1, assert.exception=1, zend.assertions=1, error_reporting=-1, log_errors_max_len=0, display_errors=On

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
        compiler:
          - default
        dependencies:
          - highest
        env:
          - DB_HOST: "127.0.0.1"
          - DB_USER: ${{ secrets.RootPassword }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: configure mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '5.7'
          mysql database: 'testing'
          mysql root password: ${{ secrets.RootPassword }}

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          ini-values: ${{ env.PHP_INI_VALUES }}
          tools: none

      - name: Install highest dependencies with composer
        if: matrix.dependencies == 'highest'
        run: php ./tools/composer update --no-ansi --no-interaction --no-progress

      - name: Run tests with phpunit
        run: php ./vendor/bin/phpunit