

name: CI

on:
  push:
    branches: [ develop, dev-*, master ]
  pull_request:
    branches: [ develop, dev-*, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: [ 5.6.*, 5.7.*, 5.8.*, 6.*, 7.* ]
        php: [7.2, 7.3, 7.4, 8.0 ]
        mysql: [5.7, 8.0]
        exclude:
          - laravel: 5.6.*
            php: 8.0  # incompatible
          - laravel: 5.7.*
            php: 8.0  # incompatible
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: testing
          options: >-
            --health-cmd="mysqladmin ping --silent"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=3

    name: Laravel ${{ matrix.laravel }} (PHP ${{ matrix.php }})
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo, sqlite, curl, dom
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit

