

name: CI

on:
  push:
    branches: [ develop, dev-*, master ]
  pull_request:
    branches: [ develop, dev-*, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - laravel: 5.6.*
            php: 7.1
          - laravel: 5.7.*
            php: 7.1
          - laravel: 5.8.*
            php: 7.2
          - laravel: 6.*
            php: 7.3
          - laravel: 7.*
            php: 7.4

    name: Laravel ${{ matrix.laravel }} (PHP ${{ matrix.php }})
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo, sqlite, curl, dom
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit

